name: Check Tokens Code

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.12.0
        with:
          components: clippy,rustfmt

      - name: Check Formatting
        run: >
          cargo fmt
          --all
          --check

      - name: Lint with Clippy
        run: >
          cargo clippy
          --all-targets
          --all-features
          --no-deps
          --
          --deny warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.12.0

      - name: Run Tests
        run: >
          cargo test
          --all-targets
          --all-features

