name: Release Tokens

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Install musl
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.12.0
        with:
          target: x86_64-unknown-linux-musl

      - name: Build binary
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Zip binary
        run: zip tokens ./target/x86_64-unknown-linux-musl/release/tokens -j

      - name: Release Tokens
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/'))
        uses: softprops/action-gh-release@v1
        with:
          files: tokens.zip

