name: CI

on:
  push:
  pull_request:

jobs:
  code:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/_code.yml

  release:
    needs: code
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/_release.yml

  coverage:
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository) && !(startsWith(github.ref, 'refs/heads/release-please'))
    needs: code
    uses: ./.github/workflows/_coverage.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release_please:
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main')
    uses: ./.github/workflows/_release_please.yml
    secrets:
      release_please_token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
    permissions:
      contents: write
      pull-requests: write

